# -*- coding: utf-8 -*-
"""КТ2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19SSBl1iRqdn0Vmy78fU6VPxijbX81xbr
"""

#1
age = int(input())
year = (2024)
print("Ваш текущий возраст: ", year - age )
print("Через 10 лет вам будет: ", year - age + 10)

#2.1
level = int(input("Уровень энергии: "))
if level %2 == 0:
 print("Щит активен")
else:
  print("Щит отключен")

#3
korg =int(input("Исходные кординаты: "))
left_shift = korg << 2
right_shift = korg >>1
print("исходное число: ", korg )
print("подбитый сдвиг влево на 2: ", left_shift)
print("подбитый сдвиг вправо на 2: ", right_shift)

#4
ttr = int(input("Введите значение регистра: "))
ppr = int(input("Введите бит (не менее 0): "))
if ttr & (1<<ppr):
 print("Бит", ppr , "установлен(1)")
else:
  print("Бит",ppr, "cброшен (0)")

#2.2 задание
level = int(input("Уровень энергии: "))
if level &(1<<0) == 0:
    print("Щит активен")
else:
    print("Щит не активен")